namespace FSUIPC;

public enum FSUIPCError
{
	FSUIPC_ERR_OK = 0,
	FSUIPC_ERR_OPEN = 1,
	FSUIPC_ERR_NOFS = 2,
	FSUIPC_ERR_REGMSG = 3,
	FSUIPC_ERR_ATOM = 4,
	FSUIPC_ERR_MAP = 5,
	FSUIPC_ERR_VIEW = 6,
	FSUIPC_ERR_VERSION = 7,
	FSUIPC_ERR_WRONGFS = 8,
	FSUIPC_ERR_NOTOPEN = 9,
	FSUIPC_ERR_NODATA = 10,
	FSUIPC_ERR_TIMEOUT = 11,
	FSUIPC_ERR_SENDMSG = 12,
	FSUIPC_ERR_DATA = 13,
	FSUIPC_ERR_RUNNING = 14,
	FSUIPC_ERR_SIZE = 15,
	FSUIPC_ERR_WRITE_OVERFLOW = 999,
	FSUIPC_KEY_SLOTS_FULL = 65536,
	FSUIPC_BUTTON_SLOTS_FULL = 65537,
	FSUIPC_PARENT_MENU_NOT_FOUND = 65538,
	FSUIPC_TYPE_NOT_SUPPORTED = 65539,
	FSUIPC_WRITE_OFFSET_NEVER_READ = 65540,
	FSUIPC_MAKERUNWAYS_FILES_MISSING = 65541,
	FSUIPC_NO_DATABASE = 65542
}
